import { colors } from './colors';

// The Banker Lapp mark: a 1960s cigar-bodied Grand Prix car in pixel art.
//
// A vintage racer rather than a modern F1 car because the whole palette is
// Vintage Racing — oxblood bodywork, a cream flank stripe, brass wire wheels and
// exhausts. It also draws far better at icon sizes: a modern car's wings and
// bargeboards turn to mush below about 64px, where a cigar hull stays readable.
//
// This file is the single source of truth for the artwork. It is consumed by:
//   · PixelSprite / PixelCar / PixelCarLoader — the in-app logo and loader
//   · scripts/generate-icons.py — every PNG icon, the splash art and the
//     pre-hydration GIF, all regenerated by parsing the arrays below
// Edit the grids here and re-run that script; never hand-edit the PNGs.

// Each character maps to one colour. '.' is transparent.
export const PIXEL_PALETTE: Record<string, string> = {
  o: '#0A0907',           // outline / the gap between spokes
  B: colors.f1Red,        // oxblood bodywork
  b: '#7A1D14',           // bodywork in shadow (underside)
  h: '#C4402F',           // bodywork catching light (engine cover)
  G: colors.brass,        // brass: spokes, exhausts, nose cap
  g: colors.brassDim,     // brass in shadow / wheel hub
  C: colors.cream,        // cream flank stripe, driver, helmet
  T: colors.bgCard,       // tyre carcass
  t: '#3A362F',           // tyre sidewall — a shade up from the carcass so the
                          // wheel still reads as a wheel against warm carbon
};

// The hull, drawn as though the wheels were not there: the wheels are a separate
// sprite stamped on top, so the loader can swap wheel frames without touching
// the body. The last two rows are blank because only the wheels reach that low.
export const CAR_BODY = [
  '.................CCC..................',
  '.................CBC..................',
  '...........hhhhhhCCCoooooG............',
  '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB....',
  '.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..',
  '.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCG',
  'GGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb',
  'ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..',
  '......................................',
  '......................................',
];

// Two wheel frames, the spokes 22.5° apart.
//
// The wheel is NOT animated with a rotate transform. Eight spokes are
// 45°-symmetric, so rotating by 45° lands on an identical image and a stepped
// spin would look frozen; anything in between resamples the sprite and destroys
// the crisp pixel edges. Swapping between two hand-exact frames is how pixel art
// has always done wheels, and it stays sharp at any scale.
export const CAR_WHEEL_FRAMES = [
  [
    '...ttt...',
    '.ttTTTtt.',
    '.tGoGoGt.',
    'tToGGGoTt',
    'tTGGgGGTt',
    'tToGGGoTt',
    '.tGoGoGt.',
    '.ttTTTtt.',
    '...ttt...',
  ],
  [
    '...ttt...',
    '.ttTTTtt.',
    '.toGoGot.',
    'tTGGGGGTt',
    'tToGgGoTt',
    'tTGGGGGTt',
    '.toGoGot.',
    '.ttTTTtt.',
    '...ttt...',
  ],
];

export const CAR_W = CAR_BODY[0].length;   // 38
export const CAR_H = CAR_BODY.length;      // 11
export const WHEEL_SPAN = CAR_WHEEL_FRAMES[0].length; // 9

// Where each wheel's centre sits on the body grid.
export const WHEEL_CENTERS = [
  { cx: 8, cy: 6 },
  { cx: 29, cy: 6 },
];

// Top-left offset, in grid cells, for a wheel sprite centred on (cx, cy).
export const wheelOffset = ({ cx, cy }: { cx: number; cy: number }) => ({
  x: cx - (WHEEL_SPAN - 1) / 2,
  y: cy - (WHEEL_SPAN - 1) / 2,
});
